<error errorId="9d33c74c-23df-480e-b9d8-dc45996812cd" host="DESKTOP-4RB83N4" type="System.Exception" message="This is a test exception" source="Petzey.Backend.Appointment.Data" detail="System.Exception: This is a test exception&#xD;&#xA;   at Petzey.Backend.Appointment.Data.Repository.AppointmentRepository.getFeedbackByAppointmrntId(Int32 id) in C:\Users\PANDURANGA\source\repos\Petzey.Backend.Appointment\Petzey.Backend.Appointment.Data\Repository\AppointmentRepository.cs:line 487&#xD;&#xA;   at Petzey.Backend.Appointment.API.Controllers.FeedbackController.GetFeedback(Int32 id) in C:\Users\PANDURANGA\source\repos\Petzey.Backend.Appointment\Petzey.Backend.Appointment.API\Controllers\FeedbackController.cs:line 37" time="2024-04-28T14:25:56.2415982Z" />