<error errorId="71aef2d3-c7b8-4619-8502-d28e14b9dcf2" host="DESKTOP-4RB83N4" type="System.Exception" message="This is a test exception" source="Petzey.Backend.Appointment.Data" detail="System.Exception: This is a test exception&#xD;&#xA;   at Petzey.Backend.Appointment.Data.Repository.AppointmentRepository.getFeedbackByAppointmrntId(Int32 id) in C:\Users\PANDURANGA\source\repos\Petzey.Backend.Appointment\Petzey.Backend.Appointment.Data\Repository\AppointmentRepository.cs:line 481" time="2024-04-28T14:25:56.2278682Z" />