<error errorId="7eac9ad3-210b-4558-ade3-0dc194b6668b" host="DESKTOP-4RB83N4" type="System.Exception" message="This is a test exception" source="Petzey.Backend.Appointment.Data" detail="System.Exception: This is a test exception&#xD;&#xA;   at Petzey.Backend.Appointment.Data.Repository.AppointmentRepository.getFeedbackByAppointmrntId(Int32 id) in C:\Users\PANDURANGA\source\repos\Petzey.Backend.Appointment\Petzey.Backend.Appointment.Data\Repository\AppointmentRepository.cs:line 481" time="2024-04-28T14:26:36.3614166Z" />